code-gen output="test/test.spec.ts":
  npx playwright codegen --output {{output}}

automate-uit-tkb:
  node ./automate/uit-tkb.js

test *args="":
  npx playwright test {{args}}

test-debug *args="":
  npx playwright test --debug {{args}}

test-ui *args="":
  npx playwright test --ui {{args}}

report:
  npx playwright show-report
